### PR TITLE
Add bindings for GDAL 3.10, and regenerate the old ones

### PR DESCRIPTION
**Pull request by lnicola**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/gdal/blob/master/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

**Comment by lnicola** [comment]
```
thread 'metadata::tests::test_md_iter' panicked at src/metadata.rs:406:9:
assertion failed: ds.metadata().any(|e| e.domain == "DERIVED_SUBDATASETS")
```

Huh

**Comment by lnicola** [comment]
r? @jdroenner

Best reviewed commit-by-commit, I got a little carried away.

**Comment by jdroenner** [comment]
looks good :)

**Comment by lnicola** [comment]
Thanks, I'll merge this, then.

I'm thinking we could also drop pre-3.4 support, which will remove a couple dozen `cfg`s.

**Comment by jdroenner** [comment]
> I'm thinking we could also drop pre-3.4 support, which will remove a couple dozen cfgs.

we should do that :)

**Pull request merged**
