### PR TITLE
Add `Feature::c_feature`

### PR DESCRIPTION
**Pull request by lnicola**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/gdal/blob/master/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

**Comment by lnicola** [comment]
r? anyone?

**Comment by jdroenner** [comment]
we could think about the pointer exposure in general. maybe such a method should be unsafe?

**Comment by lnicola** [comment]
I wanted to do a follow-up PR for that. I don't think they need to be unsafe. In rust you, the place where you dereference a pointer is unsafe, not where you create it.

So if the feature is valid, there's no reason for this method to be unsafe. And if it's not valid, it was created by unsafe code.

**Comment by lnicola** [comment]
Added `unsafe`, so it can be merged before deciding on all of the others.

**Pull request merged**
