### PR TITLE
Make clippy happy

### PR DESCRIPTION
**Pull request by lnicola**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/gdal/blob/master/CODE_OF_CONDUCT.md).
- [ ] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

**Comment by lnicola** [comment]
This requires Rust 1.58, but I don't know what our current MSRV is.

**Review by metasim — APPROVED** [review]

**Comment by metasim** [comment]
bors d+

**Comment by lnicola** [comment]
bors r=metasim

**Pull request merged**
