### PR TITLE
prepare 0.16.0 changelog + version

### PR DESCRIPTION
**Pull request by jdroenner**
- [x ] I agree to follow the project's [code of conduct](https://github.com/georust/gdal/blob/master/CODE_OF_CONDUCT.md).
- [x ] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

**Comment by lnicola** [comment]
The whitespace changes break the formatting:

image

(not that I find this layout great, but at least it's consistent)

And maybe we should publish it as 0.15.1 and yank 0.15.0?

**Comment by jdroenner** [comment]
0.15.1 vs 0.16.0 is a good question. Since there is a breaking change we should name it 0.16.0. Using 0.15.1 could cause some code to stop compiling but who ever uses that code should change it anyway :sweat:  I'm open for suggestions what version number to pick.

**Comment by lnicola** [comment]
I think it's fine if we yank it and publish 0.15.1, but let's just skip to 0.16.0, as it seems that a lot of people don't really like yanking. I had some more planned breaking changes, but version numbers are free :-).

**Comment by jdroenner** [comment]
yes will do. We need to bump gdal-sys to 0.9.1 because we changed the bindgen version. Should we also bump the dependencies for the gdal crate?

**Pull request merged**
