### PR TITLE
.github/workflows/ci.yml: run 'cargo valgrind test --lib'

### PR DESCRIPTION
**Pull request by rouault**
- [X] I agree to follow the project's [code of conduct](https://github.com/georust/gdal/blob/master/CODE_OF_CONDUCT.md).
- [ ] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

**Comment by lnicola** [comment]
I expected this to be slower, but 30 seconds isn't bad at all.

**Review by lnicola — APPROVED** [review]

**Comment by lnicola** [comment]
I'm thinking it might be a good idea to run this in the 3.8 container, since LTS might not have some of the APIs (like MD) we've implemented.

**Comment by lnicola** [comment]
Great, we can disable it for now.

https://github.com/georust/gdal/tree/master/gdal-sys#build might help with linking.

**Comment by lnicola** [comment]
Not sure if that, but we might be leaking the data type in the error case at https://github.com/georust/gdal/blob/master/src/raster/mdarray.rs#L166.

**Comment by rouault** [comment]
ok, the leak in read_into_slice() is fixed now, but there's a "system leak" related to threads & TLS, that is IMHO a false positive. But I can't find an option to specify a Valgrind suppression file to cargo valgrind. I guess we need to skip 3.8.1 testing for now

**Comment by lnicola** [comment]
Yeah, let's disable it. I'll merge this in the morning.

**Comment by rouault** [comment]
> Yeah, let's disable it. I'll merge this in the morning.

I've dropped the 3.8.1 related commit

**Comment by lnicola** [comment]
Funny, I don't get the TLS leak on my system (Gedora 39, GDAL 3.7.3).

I think we can pass in a suppressions file with `VALGRINDFLAGS="--suppressions=gdal.supp" cargo valgrind test`.

**Pull request merged**
