### PR TITLE
Prebuilt 34

### PR DESCRIPTION
**Pull request by geohardtke**
Hi there,
I'd like to contribute the pre built bindings for the new 3.4 version of GDAL.

### CODE REVIEW

**Comment by lnicola** [comment]
I'd like to merge this tomorrow unless anyone objects.

**Comment by jdroenner** [comment]
i guess we have to adapt these tests first

**Comment by lnicola** [comment]
Is anyone opposed to dropping the `trybuild` thing? It very fragile, especially when trying to support multiple compiler versions, because the error messages sometimes change.

**Comment by jdroenner** [comment]
there is already a discussion here: https://github.com/georust/gdal/pull/234
i'm not against dropping it if we can't make it work

**Comment by jdroenner** [comment]
now we have both options #237

**Comment by jdroenner** [comment]
we should first try to adapt the test. if it is not maintainable,, e.g. if it fails again ext week, then we can drop it.

**Pull request merged**
