### PR TITLE
Added a more ergonomic means of accessing GDAL version properties.

### PR DESCRIPTION
**Pull request by metasim**
- [X] I agree to follow the project's [code of conduct](https://github.com/georust/gdal/blob/master/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

This PR is of minor impact, but does provide some quality-of-life benefits when building systems which need to dynamically check and verify the version of GDAL available at runtime. 

GDAL's native query mechanism uses magical tokens that requires either brute memory, or repeated digging through API docs to fetch the particular version property needed. This PR aims to provide a slightly more principled approach to querying this information via a new `enum` called `VersionInfo`. It does not change the existing mechanism, only provides an alternative.

### CODE REVIEW

**Comment by lnicola** [comment]
I know that you wanted to make debug-printing to work, but it seems quite convoluted for what it does. I'd be fine with a more lightweight like:

```rust
pub struct VersionInfo(pub &'static str);

impl VersionInfo {
    const RELEASE_NAME: VersionInfo = VersionInfo("RELEASE_NAME");
    // ...

    fn get_version_info(&self) -> String { todo!() }

    fn all() -> String { todo!() }
}
```

Let's see how the others feel about it.

**Comment by metasim** [comment]
@lnicola I turned down the "clever" volume and implemented a more direct approach. What do you think?

**Review by lnicola — APPROVED** [review]

**Comment by lnicola** [comment]
Sure, looks good. r? @jdroenner

**Comment by metasim** [comment]
bors r=lnicola

**Pull request merged**
