### PR TITLE
Bump edition to 2021 & update changelog to release 0.12

### PR DESCRIPTION
**Pull request by jdroenner**
- [x ] I agree to follow the project's [code of conduct](https://github.com/georust/gdal/blob/master/CODE_OF_CONDUCT.md).
- [ x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

**Comment by lnicola** [comment]
I think we also need to bump the version.

**Comment by jdroenner** [comment]
in the cargo toml? i  think the  cargo release tool will do  that

**Comment by lnicola** [comment]
Oh, okay.

**Pull request merged**
