### PR TITLE
Remove test failing on GDAL 3.6

### PR DESCRIPTION
**Pull request by lnicola**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/gdal/blob/master/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

**Comment by lnicola** [comment]
I'm not sure what this is testing, but it no longer works. Maybe VSI now allows files without a name.

```
---- vsi::tests::unable_to_create stdout ----
thread 'vsi::tests::unable_to_create' panicked at 'called `Result::unwrap_err()` on an `Ok` value: ()', src/vsi.rs:298:61
```

**Comment by lnicola** [comment]
Yeah, it's intentional: https://github.com/OSGeo/gdal/blob/master/NEWS.md#port.

**Review by metasim — APPROVED** [review]

**Pull request merged**
