### PR TITLE
Wait for `osgeo/gdal` tests to complete

### PR DESCRIPTION
**Pull request by lnicola**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/gdal/blob/master/CODE_OF_CONDUCT.md).
- [ ] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

Not sure if this was intentional or not, but it seems like a good idea to wait at least for one of those versions.

And we should probably have a policy for which versions we test on.

### CODE REVIEW

**Comment by jdroenner** [comment]
good catch. Maybe the last three minor versions? My current policy is to include the GDAL version in the latest Ubuntu LTS...

**Review by jdroenner — APPROVED** [review]

**Comment by jdroenner** [comment]
bors merge

**Comment by lnicola** [comment]
> My current policy is to include the GDAL version in the latest Ubuntu LTS...

Sorry, what do you mean?

 - that we should test GDAL up to 3.4.1 (from `jammy`) on CI
 - that you try to package GDAL for Debian or Ubuntu so that the LTS picks up the latest version at the time it gets released
 - that you're hoping to package newer GDAL versions for Ubuntu LTS after it gets released (which isn't possible AFAIL)

**Comment by jdroenner** [comment]
oh what i mean is that there should be a CI run that uses the same GDAL version as shipped with the latest Ubuntu LTS. We / I mainly work on Ubuntu and therefore this is the most important CI run for me.

There is no real policy which other versions should be tested. We should discuss this. I guess we could remove the CI for GDAL 3.2 at some point...

**Pull request merged**
