### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by jdroenner**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/gdal/blob/master/CODE_OF_CONDUCT.md).
- [ ] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

### CODE REVIEW

**Comment by lnicola** [comment]
It's broken, isn't it?

**Comment by jdroenner** [comment]
bors? I guess the new CI is too much for bors.

**Comment by lnicola** [comment]
I guess https://github.com/georust/gdal/blob/master/bors.toml needs to be updated with the job names from the workflow.

**Comment by jdroenner** [comment]
uh good catch

**Comment by jdroenner** [comment]
bors try

**Comment by lnicola** [comment]
That won't work, you need to update `bors.toml` on `master` before using it.

**Comment by jdroenner** [comment]
thats strange

**Pull request merged**
