### PR TITLE
Add prebuilt-bindings GDAL 2.3 and GDAL 2.4.

### PR DESCRIPTION
**Pull request by rochamatcomp**
Prebuilt-bindings for GDAL 2.3.3 and GDAL 2.4.1
Update bindgen to version 0.48.

### CODE REVIEW

**Comment by pka** [comment]
Looks good to me!
@jdroenner: is it ok, when I merge?
@frewsxcv: who has permissions to run bors?

**Comment by jdroenner** [comment]
yes, of course. Feel free to merge :)

**Comment by frewsxcv** [comment]
@pka just granted you bors permissions – can you try again?

**Pull request merged**
