### PR TITLE
Refactoring `vector` module for better maintainability and extensibility.

### PR DESCRIPTION
**Pull request by metasim**
- [X] I agree to follow the project's [code of conduct](https://github.com/georust/gdal/blob/master/CODE_OF_CONDUCT.md).
- [NA] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

Refactoring to improve maintainability of vector module.

Changes include:
* Grouping methods of similar purpose into separate files
* Putting associated tests in the same file as the implementation
* Adding or expanding documentation on existing methods
* Normalizing documentation patterns and format.

Intent was to not have any breaking changes.

### CODE REVIEW

**Review by lnicola — APPROVED** [review]
LGTM overall, but I can't say for sure :sweat_smile:.

One naming nit: should we use something like `set` instead of `binary`? And `formats` (:bike: :house:) instead of `text`?

**Comment by metasim** [comment]
> One naming nit

Not a nit... I've already renamed those 5 times. 🙈

**Review by jdroenner — APPROVED** [review]

**Comment by metasim** [comment]
@lnicola @jdroenner I'm going to merge this, and then in a separate PR implement `union`, `difference`, `symmetric_difference`, etc. in the new `set` module.

**Comment by lnicola** [comment]
> [NA] I added an entry to CHANGES.md if knowledge of this change could be valuable to users.

image

Anyway, we can probably merge this.

bors d+

**Comment by lnicola** [comment]
Actually, maybe there's no breaking changes?

bors r+

**Pull request merged**
