### PR TITLE
Fix bors integration

### PR DESCRIPTION
**Pull request by michaelkirk**
- [x] I agree to follow the project's [code of conduct](https://github.com/georust/gdal/blob/master/CODE_OF_CONDUCT.md).
- [x] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

I think the elements in `status` need to match all the GH Action job names we require to succeed.

### CODE REVIEW

**Comment by michaelkirk** [comment]
bors try

**Comment by lnicola** [comment]
Is it stuck?

**Comment by michaelkirk** [comment]
bors try-

**Comment by michaelkirk** [comment]
bors try

**Comment by michaelkirk** [comment]
> Build failed:

woohoo! I think that's actually what we want to see at this point, because it means bors is working. The clippy lint causing the build failure is fixed in #205.

So you can merge #205 first, or manually merge this while the build is still broken, or whatever else you like.

**Comment by michaelkirk** [comment]
bors retry

😒

**Comment by michaelkirk** [comment]
bors retry

😒 🤖

**Pull request merged**
